version: '3'
services:
  node:
    container_name: pt1-api
    depends_on:
      - mariadb
    build:
      context: ../
      dockerfile: ./devDocker/api/Dockerfile
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      DB_PING_HOST: "pt1-db"
      DB_PING_USER: "pt1"
      DB_PING_PASS: "pt1"
    env_file:
      - ../api/.env
    ports:
      - 23000:3000

  react:
    image: node:16.17.0-slim
    container_name: pt1-web
    volumes:
      - ../web:/app
    working_dir: /app
    tty: true
    command: /bin/bash -c "npm run start"
    ports:
      - 8080:8080
    environment:
      TZ: "Asia/Tokyo"
      HOST: "www.localhost.pt1.r253hmdryou.dev"

  proxy:
    image: nginx:stable
    container_name: pt1-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/www.localhost.r253hmdryou.dev.cert:/etc/nginx/www.localhost.r253hmdryou.dev.cert
      - ./proxy/api.localhost.r253hmdryou.dev.cert:/etc/nginx/api.localhost.r253hmdryou.dev.cert
    ports:
      - 443:443

  mariadb:
    image: mariadb:10.6.8
    container_name: pt1-db
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: "pt1"
      MYSQL_DATABASE: "pt1"
      MYSQL_USER: "pt1"
      MYSQL_PASSWORD: "pt1"
    env_file:
      - ../api/.env
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql

  jestdb:
    image: mariadb:10.6.8
    container_name: jest-db
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: "pt1"
      MYSQL_USER: "pt1"
      MYSQL_PASSWORD: "pt1"
    env_file:
      - ../api/.env.test
    ports:
      - 13306:3306
