root: true
extends:
- "eslint:recommended"
- "plugin:eslint-comments/recommended"
- "plugin:@typescript-eslint/eslint-recommended"
- "plugin:@typescript-eslint/recommended"
- "plugin:security/recommended"
env:
  commonjs: true
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
plugins:
- "@typescript-eslint"
- "eslint-comments"
- "security"
rules:
  brace-style: error
  comma-dangle:
  - error
  - always-multiline
  comma-spacing:
  - error
  - after: true
    before: false
  comma-style:
  - error
  - last
  eol-last: error
  eqeqeq: error
  indent:
  - error
  - tab
  no-multi-spaces: error
  no-multiple-empty-lines:
  - error
  - max: 1
  no-spaced-func: error
  quotes:
  - error
  - double
  - allowTemplateLiterals: true
    avoidEscape: true
  require-jsdoc: error
  semi:
  - error
  - always
  space-before-function-paren:
  - error
  - never
  space-in-parens:
  - error
  - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
  - error
  - always
  valid-jsdoc:
  - error
  - prefer:
      arg: param
      argument: param
      return: returns
    requireParamType: false
    requireReturn: true
    requireReturnType: false

  # @typescript-eslint plugin
  "@typescript-eslint/explicit-function-return-type": error
  "@typescript-eslint/no-unused-vars":
  - error
  - args: all
    argsIgnorePattern: "^_"
    varsIgnorePattern: "^_"

  # eslint-comments plugin
  "eslint-comments/disable-enable-pair": 0
  "eslint-comments/no-unlimited-disable": 0
