root: true
settings:
  react:
    version: "detect"
env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
- "eslint:recommended"
- "plugin:react/recommended"
- "plugin:@typescript-eslint/eslint-recommended"
- "plugin:@typescript-eslint/recommended"
- "plugin:security/recommended"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
plugins:
- react
- '@typescript-eslint'
- "security"
rules:
  brace-style: error
  comma-dangle:
  - error
  - always-multiline
  comma-spacing:
  - error
  - after: true
    before: false
  comma-style:
  - error
  - last
  eol-last: error
  eqeqeq: error
  indent:
  - error
  - tab
  no-multi-spaces: error
  no-multiple-empty-lines:
  - error
  - max: 1
  no-spaced-func: error
  quotes:
  - error
  - double
  - allowTemplateLiterals: true
    avoidEscape: true
  semi:
  - error
  - always
  space-before-function-paren:
  - error
  - never
  space-in-parens:
  - error
  - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
  - error
  - always
  valid-jsdoc:
  - error
  - prefer:
      arg: param
      argument: param
      return: returns
    requireParamType: false
    requireReturn: true
    requireReturnType: false

  # @typescript-eslint plugin
  "@typescript-eslint/no-unused-vars":
  - error
  - args: all
    argsIgnorePattern: "^_"
    varsIgnorePattern: "^_"
  "@typescript-eslint/no-empty-function": off

  # React plugin
  "react/react-in-jsx-scope": "off"
  "react/no-unknown-property":
  - 2
  - ignore:
    - css
